apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-notification-service
  labels:
    app: todo-notification-service
spec:
  replicas: {{ .Values.notificationService.replicaCount }}
  selector:
    matchLabels:
      app: todo-notification-service
  template:
    metadata:
      labels:
        app: todo-notification-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "notification-service"
        dapr.io/app-port: "8001"
        dapr.io/config: "dapr-config"
    spec:
      containers:
        - name: notification-service
          image: "{{ .Values.notificationService.image.repository }}:{{ .Values.notificationService.image.tag }}"
          imagePullPolicy: {{ .Values.notificationService.image.pullPolicy }}
          ports:
            - containerPort: 8001
          env:
            {{- range $key, $value := .Values.notificationService.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
