apiVersion: v1
kind: Service
metadata:
  name: todo-scheduler-service-svc
  labels:
    app: todo-scheduler-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.schedulerService.service.port }}
      targetPort: 8002
      protocol: TCP
  selector:
    app: todo-scheduler-service
