openapi: 3.1.0
info:
  title: Todo Full-Stack API
  description: |
    Secure, scalable FastAPI backend for multi-user Todo application with JWT authentication and Neon PostgreSQL storage.

    ## Authentication
    All endpoints require JWT authentication via `Authorization: Bearer <token>` header.
    Tokens are issued by Better Auth frontend and verified using shared secret.

    ## User Isolation
    Users can only access their own tasks. Cross-user access attempts return 403 Forbidden.

    ## Error Responses
    All errors return `{"detail": "error message"}` format.
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.example.com
    description: Production server

tags:
  - name: Tasks
    description: Task CRUD operations

security:
  - BearerAuth: []

paths:
  /api/{user_id}/tasks:
    get:
      tags:
        - Tasks
      summary: List all tasks for authenticated user
      description: |
        Retrieves all tasks belonging to the authenticated user.
        Returns tasks ordered by creation date (newest first).
      operationId: listTasks
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match authenticated user from JWT)
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

    post:
      tags:
        - Tasks
      summary: Create new task
      description: Creates a new task for the authenticated user
      operationId: createTask
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match authenticated user from JWT)
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '422':
          $ref: '#/components/responses/ValidationError'

  /api/{user_id}/tasks/{id}:
    get:
      tags:
        - Tasks
      summary: Get single task by ID
      description: Retrieves a specific task by its ID
      operationId: getTask
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match authenticated user from JWT)
          schema:
            type: integer
            example: 1
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: integer
            example: 42
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      tags:
        - Tasks
      summary: Update task title and/or description
      description: Updates an existing task's title and/or description
      operationId: updateTask
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match authenticated user from JWT)
          schema:
            type: integer
            example: 1
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: integer
            example: 42
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/ValidationError'

    delete:
      tags:
        - Tasks
      summary: Delete task
      description: Permanently deletes a task
      operationId: deleteTask
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match authenticated user from JWT)
          schema:
            type: integer
            example: 1
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: integer
            example: 42
      responses:
        '204':
          description: Task deleted successfully (no content)
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/{user_id}/tasks/{id}/complete:
    patch:
      tags:
        - Tasks
      summary: Toggle task completion status
      description: |
        Toggles the task's completed status.
        If currently false, sets to true. If currently true, sets to false.
      operationId: toggleTaskCompletion
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match authenticated user from JWT)
          schema:
            type: integer
            example: 1
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: integer
            example: 42
      responses:
        '200':
          description: Task completion status toggled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWT token issued by Better Auth.
        Include in Authorization header: `Bearer <token>`

  schemas:
    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 1000
          description: Task title
          example: "Complete project documentation"
        description:
          type: string
          maxLength: 5000
          nullable: true
          description: Optional task description
          example: "Write comprehensive API documentation for the todo backend"

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 1000
          nullable: true
          description: Updated task title
          example: "Complete project documentation (updated)"
        description:
          type: string
          maxLength: 5000
          nullable: true
          description: Updated task description
          example: "Write and review comprehensive API documentation"

    TaskResponse:
      type: object
      required:
        - id
        - title
        - description
        - completed
        - owner_id
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          description: Unique task identifier
          example: 42
        title:
          type: string
          description: Task title
          example: "Complete project documentation"
        description:
          type: string
          nullable: true
          description: Task description (null if not provided)
          example: "Write comprehensive API documentation for the todo backend"
        completed:
          type: boolean
          description: Completion status
          example: false
        owner_id:
          type: integer
          description: ID of user who owns this task
          example: 1
        created_at:
          type: string
          format: date-time
          description: Task creation timestamp (UTC, ISO 8601)
          example: "2026-01-23T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp (UTC, ISO 8601)
          example: "2026-01-23T10:30:00Z"

    ErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message
          example: "Task not found"

    ValidationErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: array
          items:
            type: object
            properties:
              loc:
                type: array
                items:
                  oneOf:
                    - type: string
                    - type: integer
                description: Location of error in request
                example: ["body", "title"]
              msg:
                type: string
                description: Error message
                example: "field required"
              type:
                type: string
                description: Error type
                example: "value_error.missing"

  responses:
    Unauthorized:
      description: Missing, invalid, or expired JWT token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Invalid or expired token"

    Forbidden:
      description: Valid JWT but attempting to access another user's resources
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Cannot access another user's tasks"

    NotFound:
      description: Requested resource does not exist
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Task not found"

    ValidationError:
      description: Request payload validation failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationErrorResponse'
          example:
            detail:
              - loc: ["body", "title"]
                msg: "field required"
                type: "value_error.missing"
