// types/task.ts
// Task entity types matching backend Task model

/**
 * Task entity representing a todo task belonging to a specific user
 * Mirrors backend Task model from backend/app/models/todo.py
 */
export type Priority = 'high' | 'medium' | 'low' | 'none';

export interface Tag {
  id: number;
  name: string;
  color: string;
}

export interface RecurrenceRule {
  id: number;
  frequency: 'daily' | 'weekly' | 'monthly' | 'custom';
  interval: number;
  days_of_week?: number[];
  end_type: 'never' | 'on_date' | 'after_n';
  end_date?: string;
  end_count?: number;
}

export interface Task {
  /** Unique task identifier (auto-generated by backend) */
  id: number;

  /** Task title (1-1000 characters, required) */
  title: string;

  /** Optional detailed description (max 5000 characters, nullable) */
  description: string | null;

  /** Completion status (default: false) */
  completed: boolean;

  /** User ID who owns this task */
  owner_id: number;

  /** Task creation timestamp (UTC, ISO 8601 format) */
  created_at: string;

  /** Last modification timestamp (UTC, ISO 8601 format) */
  updated_at: string;

  // Phase V fields
  priority: Priority;
  due_date?: string | null;
  is_overdue?: boolean;
  has_recurrence?: boolean;
  parent_task_id?: number | null;
  recurrence_rule?: RecurrenceRule | null;
  tags?: Tag[];
}

export interface Notification {
  id: number;
  user_id: string;
  task_id: number | null;
  content: string;
  notification_type: 'overdue' | 'reminder' | string;
  is_read: boolean;
  created_at: string;
}

/**
 * Data submitted when creating a new task
 * Used in task creation form
 */
export interface TaskCreateInput {
  /** Task title (required, 1-1000 characters) */
  title: string;

  /** Optional task description (max 5000 characters) */
  description?: string;

  // Phase V fields
  priority?: Priority;
  due_date?: string;
  tag_ids?: number[];
  recurrence?: Partial<RecurrenceRule>;
}

export interface TaskUpdateInput {
  title?: string;
  description?: string;
  priority?: Priority;
  due_date?: string | null;
  tag_ids?: number[];
}

export interface TaskFilters {
  query?: string;
  priority?: Priority | '';
  status?: 'all' | 'pending' | 'completed' | 'overdue';
  tag_id?: number;
  sort_by?: 'created_at' | 'due_date' | 'priority';
  sort_dir?: 'asc' | 'desc';
}
